In [5]:
import numpy as np

In [1]:
print("hi")

hi


In [8]:
a =np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b = np.array([[1,2,3], [4,5,6]])


In [9]:
zeros = np.zeros((1,2,3))
zeros 

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
nspace_array = np.linspace(0,1,5)
nspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
print(a.shape)

(3,)


In [17]:
print(b.dtype)

int64


In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])


In [19]:
print(x+y)

[5 7 9]


In [20]:
print(x*y)

[ 4 10 18]


In [21]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


In [22]:
arr = np.array([[1,2,3],[4,5,6]])


In [24]:
print(arr[0,1])

2


In [25]:
print(arr[:1])

[[1 2 3]]


In [26]:
a = np.array([10,20,30,40])
print(a[[0,2]])

[10 30]


In [27]:
print(a[-1])

40


sufian